### ISSUE TITLE
1.4.0 Release Organization

### ISSUE THREAD

**Issue by wdm0006** [scikit-learn-contrib/categorical-encoding#159]
Hey all, been away from the project for a bit, but I'm going back through all of the issues and PRs worked on recently (looks like a bunch of good progress!). Special thanks to @janmotl for all of the work as primary maintainer over the past months.

Our last release was 1.3.0 on October 14th.  Since then ya'll have:

- Sped up the TargetEncoder and LeaveOneOutEncoder w/ vectorization (significantly)
- Added support for Categorical types in many encoders
- Implemented get_feature_names in remaining transformers
- Improved testing coverage and quality
- Solved edge cases in repeated column names for some transformers
- Added support for transforming pandas Series as well as DataFrames and numpy Arrays
- Fixed inverse transform for many encoders
- Lots of smaller performance enhancements and code cleanups

Which I think is a quite full set of features to constitute a release.  I will be opening a separate issue to discuss how we as a community can improve our release cycle, but for now will be going through open issues and tagging anything that should be included before the v1.4.0 release. Any input on what should or shouldn't be completed prior to release is welcome. 

Thank you all for the work and support this year, and Happy Holidays.

**Comment by janmotl** [comment]
It has to be noted that v1.4.0 also introduces braking changes: arguments `impute_missing` and `handle_unknown` are now called `handle_missing` and `handle_unknown`. And their possible values have changed.

**Comment by wdm0006** [comment]
Hm good point, probably should be a major release then.

**Comment by amueller** [comment]
have you run ``check_estimator`` on these or is that not possible right now?

**Comment by janmotl** [comment]
It would be nice to pass 'check_estimator'.

**Comment by gammadistribution** [comment]
Hey @janmotl, do you happen to know when the new version would be released? 

If there are remaining tasks, I can help to close them if desired.

**Comment by janmotl** [comment]
@JohnnyC08 , don't you know how to deal with "errors" like:
```
======================================================================
ERROR: test_inverse_transform_BothFieldsAreReturnNanWithNan_ExpectValueError (category_encoders.tests.test_basen.TestBaseNEncoder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/scikit-learn-contrib/categorical-encoding/category_encoders/tests/test_basen.py", line 116, in test_inverse_transform_BothFieldsAreReturnNanWithNan_ExpectValueError
    enc.inverse_transform(result)
  File "/home/travis/build/scikit-learn-contrib/categorical-encoding/category_encoders/basen.py", line 287, in inverse_transform
    "the unknown category nan when encode %s" % (col,))
UserWarning: inverse_transform is not supported because transform impute the unknown category nan when encode city
```
as reported at: https://travis-ci.org/scikit-learn-contrib/categorical-encoding/jobs/491609594 ?

**Comment by JohnnyC08** [comment]
@janmotl I will pull the latest master and see if I can reproduce locally

**Comment by janmotl** [comment]
Beside the failing Travis CI (I didn't manage to reproduce the error with nosetest on my local computer), the code should be ready for release 2.0.0.

**Comment by wdm0006** [comment]
@janmotl sorry for the delay, I'll take a look at a 2.0.0 release here shortly.

**Comment by wdm0006** [comment]
@janmotl actually, to avoid delays like this in the future, it'd probably make sense to add you as a collaborator on PyPI.org right? If you send me your PyPI username I can add you to the project there.

**Comment by janmotl** [comment]
Good. My PyPI username: `janmotl`

**Comment by wdm0006** [comment]
@janmotl should be a maintainer there now, please check and let me know.

**Comment by janmotl** [comment]
Thank you, @wdm0006. I am now a maintainer. Do we have a procedure how to make a release?

**Comment by wdm0006** [comment]
@janmotl not very formally, I usually just up the version in setup.py, run update_docs.sh and use twine to publish to pypi. Would you like to give that a shot and I can help out with any issues that crop up.

**Comment by janmotl** [comment]
Done. Could you check it?
