### ISSUE TITLE
TargetEncoder inside ColumnTransformer

### ISSUE THREAD

**Issue by MartykQ** [scikit-learn-contrib/categorical-encoding#206]
I am having some problems with using TaregetEncoder inside of sciki's ColumnTransformer. I saw people having simmiliar issues with using Pipelines/ColumnTranformer but have not found any solution. 

```
df = pd.read_csv('data.csv')

ct = ColumnTransformer(
    [
        ('standard', StandardScaler(), ['comments']),
        ('target', TargetEncoder(), ['severity'])
    ]
)

```

Above code gives me:

```

/home/user/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/home/user/anaconda3/lib/python3.7/site-packages/sklearn/base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
  
Traceback (most recent call last):
  File "/home/user/Desktop/ML_PROJECT/note.py", line 23, in <module>
    ct.fit_transform(pd_df)
  File "/home/user/anaconda3/lib/python3.7/site-packages/sklearn/compose/_column_transformer.py", line 449, in fit_transform
    result = self._fit_transform(X, y, _fit_transform_one)
  File "/home/user/anaconda3/lib/python3.7/site-packages/sklearn/compose/_column_transformer.py", line 393, in _fit_transform
    fitted=fitted, replace_strings=True))
  File "/home/user/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 920, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/user/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/user/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/user/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/home/user/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/home/user/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/user/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/user/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py", line 614, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/home/user/anaconda3/lib/python3.7/site-packages/category_encoders/target_encoder.py", line 251, in fit_transform
    return self.fit(X, y, **fit_params).transform(X, y)
  File "/home/user/anaconda3/lib/python3.7/site-packages/category_encoders/target_encoder.py", line 117, in fit
    if X.shape[0] != y.shape[0]:
AttributeError: 'NoneType' object has no attribute 'shape'

```

**Comment by MartykQ** [comment]
I've found my mistake. I have not defined y inside ColumnTransformer fit_transform method

For everyone having issues with that one, here is my code snippet

```

pd_df = pandas.read_csv('data.csv')

ct = ColumnTransformer(
    [
        ('target', TargetEncoder(cols=['who_opened', 'who_merged'], smoothing=100, min_samples_leaf=10), ['who_opened', 'who_merged'])
    ], remainder='passthrough'
)

wut = ct.fit_transform(pd_df, y=pd_df['target'])

```

**Comment by janmotl** [comment]
Thank you. I have put the example into  `categorical-encoding/examples/column_transformer_example.py` and added an error message https://github.com/scikit-learn-contrib/categorical-encoding/commit/d9e80c08aa0343356545408d0df6310be3f6307e.
